%% Group 7
% Dimitrios Karatis (10775)

%% Problem 6
clear; close all; clc;

% Load dataset
filename = 'TMS.xlsx';
data = readtable(filename);

% Set random seed for reproducibility
rng(10)

% Keep only rows where TMS == 1
data_full = data(data.TMS == 1, :);

% Include 'Spike' variable in analysis
include_spike = true;
Group7Exe6Fun1(data_full, include_spike);

% Exclude 'Spike' variable from analysis
include_spike = false; 
Group7Exe6Fun1(data_full, include_spike);

%% Conclusions

% When the 'Spike' variable is included, all models show very low R-squared and 
% Adjusted R-squared values, indicating that the predictors do not explain EDduration well. 
% Specifically, the full model has Adjusted R-squared 0.004 and MSE 59.797, 
% the stepwise regression improves slightly with Adjusted R-squared 0.044 and MSE 61.880, 
% while LASSO shows even lower R-squared (0.013) and the highest MSE (62.575).

% When the 'Spike' variable is removed, the results improve significantly due to many 
% missing values being eliminated. The full model now has Adjusted R-squared 0.250, 
% while the stepwise model achieves the highest Adjusted R-squared (0.415) and the 
% lowest MSE (85.694), indicating a much better fit. Only two significant predictors 
% are selected, which contribute meaningfully to prediction. LASSO selects more variables, 
% but has lower Adjusted R-squared (0.246) and higher MSE (104.801).

% Overall, ignoring the 'Spike' variable leads to better model accuracy, particularly 
% with stepwise regression. This suggests that 'Spike' introduces noise rather than 
% useful information. Consequently, stepwise regression without 'Spike' provides 
% the best balance between accuracy (high Adjusted R-squared) and low error (MSE).

% For subsequent analyses, we decided NOT to use the 'Spike' variable.

% These observations are also visible in the plots generated by the function.

